name: Samples
on: [push, pull_request]
jobs:
  build:
    name: Run ${{ matrix.sample }} on GraalVM (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
        sample: ['simple','xml','sqlprovider', 'config']
      fail-fast: false
      max-parallel: 8
    steps:
      - uses: actions/checkout@v2
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{ matrix.java }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-samples-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-samples-
      - name: Print environments
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build native image
        run: ./mvnw -pl mybatis-spring-native-core,mybatis-spring-native-samples/mybatis-spring-native-sample-${{ matrix.sample }} -U -Dmaven.test.skip -Pnative clean package -Dlicense.skip=true
      - name: Run with native image
        run: ./mybatis-spring-native-samples/mybatis-spring-native-sample-${{ matrix.sample }}/target/mybatis-spring-native-sample-${{ matrix.sample }}
      - name: Run with executable jar
        run: java -jar ./mybatis-spring-native-samples/mybatis-spring-native-sample-${{ matrix.sample }}/target/mybatis-spring-native-sample-${{ matrix.sample }}-0.0.1-SNAPSHOT-exec.jar
